-- Simply add the item and the amount you want to list and you shall receive :)

ITEM_LIST = {
	{"iron-plate", 300},
	{"copper-plate", 200},
	{"electronic-circuit", 200},
	{"iron-gear-wheel", 200},
	{"inserter", 50},
	{"transport-belt", 300},
	{"small-electric-pole", 50},
	{"medium-electric-pole", 20},
	{"big-electric-pole", 20},
	{"electric-mining-drill", 8},
	{"stone-furnace", 49},
	{"assembling-machine-1", 20},
	{"pipe", 100},
	{"wooden-chest", 20},
	{"steam-engine", 10},
	{"boiler", 5},
	{"offshore-pump", 1},
	{"pipe-to-ground", 2},
	{"lab", 2},
	{"train-stop", 20},
	{"rail", 900},
	{"locomotive", 5},
	{"cargo-wagon", 10},
	{"rail-signal", 50},
	{"rail-chain-signal", 50},
	{"small-lamp", 50},
	{"car", 1},
}
